### PR TITLE
CCDEXChain - cross-chain bridge for polkadot

### PR DESCRIPTION
**Pull request by ccdex-top**
## Grant Application

This application is (select one):
- [x] Speculative (use this by default)
- [ ] an RFP response

###

This application is (select one):
- [x] Public (fully)
- [ ] Public with private finances

### Abstract

We are building a cross-chain bridge for Polkadot. The publickey algorithm used by the polkadot network is ed25519/sr25519, we want to design an algorithm based on MPC that can support distributed generation of EDDSA signature. Based on our previous work, the ECDSA distributed signature of the cross-chain bridging BTC and ETH networks has been implemented. Combined with the EDDSA algorithm, the nodes of the polkadot parallel chain can decentralized cross-chain with the BTC, ETH and other networks.

## Checklist
- [x] The [grants](https://github.com/w3f/Web3-collaboration/blob/master/grants/grants.md) document has been read and understood.
- [x] The [Google Form](https://docs.google.com/forms/d/e/1FAIpQLSfMfjiRmDQDRk-4OhNASM6BAKii7rz_B1jWtbCPkUh6N7M2ww/viewform) will be completed accurately. Note that the Google Form requires the pull request URL.
- [x] Abstract (above) is succinct and complete.
- [x] The application is being included into the correct directory: either '[targeted](https://github.com/w3f/Web3-collaboration/tree/master/grants/targeted)' or '[speculative](https://github.com/w3f/Web3-collaboration/tree/master/grants/speculative)'.
- [x] The application includes a project description.
- [x] The application includes all names of team members.
- [x] The application includes a description of the team's experience.
- [x] The application includes all necessary links (e.g. GitHub and LinkedIn)
- [x] The "Development Roadmap" section in the application has a timeline of development ("milestones").
- [x] The "Development Roadmap" section in the application has an estimate of funds required.
- [x] The "Development Roadmap" section gives an indication of the team's long term plans.
- [x] The "Development Roadmap" section includes [documentation](https://github.com/w3f/Web3-collaboration/blob/master/grants/grants.md#documentation) as a deliverable for at least one milestone.

### CODE REVIEW

**Comment by burdges** [comment]
We implemented sr25519 multi-signatures in https://github.com/w3f/schnorrkel/blob/master/src/musig.rs but never got around to doing a DKG.  We might delinearize the R values in the near future.  We've no security argument for doing this really, but sound sensible.  I think this code adapts to EdDSA cleanly, except you must argue the cofactor does not create problems.

**Comment by ccdex-top** [comment]
> We implemented sr25519 multi-signatures in https://github.com/w3f/schnorrkel/blob/master/src/musig.rs but never got around to doing a DKG. We might delinearize the R values in the near future. We've no security argument for doing this really, but sound sensible.
> 
> I think this code adapts to EdDSA cleanly, except you must argue the cofactor does not create problems. Can you make a comment on if/where the cofactor creates a concern here?

We already have a workable design, do some analysis on security, and send you an email. Detailed design and security certification will be provided later.

**Comment by burdges** [comment]
They emailed me a pdf with the naive schnorr multi-signature scheme, for which afaik nobody has ever claimed provable security.  It's vulnerable to parallel signing attacks too, which sounds doable with bridges.

**Comment by zhaojun-sh** [comment]
@burdges  Thank you for your review. We are very sorry, the pdf in the email is a simple description of the algorithm, which is easy to cause misunderstanding. First of all this is not a schnorr multi-signature.
Although ai = Hash(Ai, {A1,...,An}) is a typical feature of multi-signature, this is not a multi-signature based scheme.

In the previous pdf version, some of the algorithm details were omitted and a complete algorithm description email was resent. For complete security certification, we plan to provide it later.

**Comment by ccdex-top** [comment]
@burdges  Thank you for your review. We are very sorry, the pdf in the email is a simple description of the algorithm, which is easy to cause misunderstanding. First of all this is not a schnorr multi-signature.
Although ai = Hash(Ai, {A1,...,An}) is a typical feature of multi-signature, this is not a multi-signature based scheme.

In the previous pdf version, some of the algorithm details were omitted and a complete algorithm description email was resent. For complete security certification, we plan to provide it later.

**Pull request closed without merging**
