### PR TITLE
pull request for a new project called Bullet-Zokrates

### PR DESCRIPTION
**Pull request by danielsonggit**
## Grant Application

This application is (select one):
- [x] Speculative (use this by default)
- [ ] an RFP response

###

This application is (select one):
- [ ] Public (fully)
- [x] Public with private finances

### Abstract
2018, two Ph.D. students proposed a processing framework Zokrates based on zk-snarks for off-chain computing/on-chain verification and provided a toolchain for the entire framework on Ethereum. This project is an analogous framework based on Bullet-proof and provide toolchain for the parachain in polkadot, to enhancement the Scalability and can be used as an expansion mechanism.

## Checklist
- [x] The [grants](https://github.com/w3f/Web3-collaboration/blob/master/grants/grants.md) document has been read and understood.
- [x] The [Google Form](https://docs.google.com/forms/d/e/1FAIpQLSfMfjiRmDQDRk-4OhNASM6BAKii7rz_B1jWtbCPkUh6N7M2ww/viewform) will be completed accurately. Note that the Google Form requires the pull request URL.
- [x] Abstract (above) is succinct and complete.
- [x] The application is being included into the correct directory: either '[targeted](https://github.com/w3f/Web3-collaboration/tree/master/grants/targeted)' or '[speculative](https://github.com/w3f/Web3-collaboration/tree/master/grants/speculative)'.
- [x] The application includes a project description.
- [x] The application includes all names of team members.
- [x] The application includes a description of the team's experience.
- [x] The application includes all necessary links (e.g. GitHub and LinkedIn)
- [x] The "Development Roadmap" section in the application has a timeline of development ("milestones").
- [x] ~~The "Development Roadmap" section in the application has an estimate of funds required.~~<br>will be inlcuded in the Google Form
- [x] The "Development Roadmap" section gives an indication of the team's long term plans.
- [x] The "Development Roadmap" section includes [documentation](https://github.com/w3f/Web3-collaboration/blob/master/grants/grants.md#documentation) as a deliverable for at least one milestone.

### CODE REVIEW

**Comment by burdges** [comment]
Why bulletproofs?

**Comment by danielsonggit** [comment]
Hi, burdges, thanks very much!

We choose Bulletproofs as our ZK protocol because :
* Bulletproofs are based on the discrete logarithm problem and have no trusted setup;
* The size of Bulletproofs are logarithmic, which is achieved through the use of an inner product argument. This feature is important to reduce the storage when verify some previous off-chain computing;
* We would like to do some optimization to reduce the time complexity;
* Without Zokrates based on  Bulletproofs currently, we would like to make some effort  to implement one as an alternative, experimental field, and tool chain for parachain. 

And as mentioned in the roadmap, M1,  we first will realize an Zokrates and relative toolchain based on zksnarks for parachain

**Comment by burdges** [comment]
I'm confused.  Zokrates is based on zkSNARKs right?  Are you reusing their code base or doing something completely new?

**Comment by danielsonggit** [comment]
So sorry for not expressing ourselves clearly!

Our project first will realize the adaptation of original Zokrates for parachain,  because it is more suitable  for Ethereum, we are afraid  there may be some little inconvenient and inefficient  for parachain.
When we accomplish  the above task, Second, we will change the zksnarks which the original zokrates based on into bulletproofs, reusing and promoting the code base. Then, we could get a toolkit based on bulletproofs providing  privacy toolchain for parachain.

**Comment by edisinovcic** [comment]
@danielsonggit ZoKrates is moving towards bellman and from libsnarks as same as ZCash. Trusted setup is definitely a problem, what could remove problem of the trusted setup are STARKs but they have their own problems and are completely different topic. 

Our team has built the plugin for Remix based on ZoKrates and if I can help with this anyhow let me know. 
By being inefficient for parachains can you explain what you mean by that?

**Comment by burdges** [comment]
@edisinovcic Cool.  :)  

Is there an issue that ZoKrates needs many different trusted setups for different projects, etc.?  

We've seen like several new universal SNARKs announced this year, sonic, plonk, marlin, etc., with presumably another improved wave coming around the next big conference deadline.  Among these, several are R1CS based like bellman, so assuming this problem exists, then ZoKrates could support both Groth16 for projects that can do a trusted setup, and one good universal SNARK for R1CS circuits for projects that lack the buy in for trusted setups.  

We could write a polkadot para-thread that made all polkadot validators participate in a trusted setup for a Groth16 circuit.  It's not quite the right threat model but it's something.  You'd ideally want independent participation based by participation in proof-of-person-hood parties perhaps.

**Comment by danielsonggit** [comment]
@edisinovcic @burdges 

Extremely grateful to you for your kindness. Just as the paper [bulletproofs](https://eprint.iacr.org/2017/1066.pdf) demonstrated, Bulletproofs is an NIZK protocol that do not need trusted setup, with shorter proofs achieved through the use of an inner product argument. And, as mentioned at the end of the paper [ZoKrates - Scalable Privacy-Preserving Off-Chain Computations](https://www.ise.tu-berlin.de/fileadmin/fg308/publications/2018/2018_eberhardt_ZoKrates.pdf), bulletproofs is another promising direction. So, we would like to make some effort to provide one for the parachain. 

<br>When we say it is inefficient for parachain, it is not to say the performance is not satisfy us, but it may could not be applied to parachain directly without any modification.  And, so do you think that our idea is sensible, possible, and workable? Or , there should be some adjustment and modification? Thanks again !

**Comment by edisinovcic** [comment]
@burdges yes, I don't think currently ZoKrates is suitable for implementing "parachain template" as it needs a trusted setup to be performed although when you mentioned that para threads could be used and only one parachain on which trusted setup would be done (if I understood you correctly) then maybe it's okay approach although from the current perspective I would rather go with @danielsonggit proposal or something similar that doesn't require a trusted setup at all. 

@danielsonggit is the idea to use ZoKrates DSL for this or what is the reason for using ZoKrates here as you are not going to use SNARKs at all?

**Comment by burdges** [comment]
@edisinovcic If you've many different circuits then there are several ways to get the trusted setups, either (a) use a universal SNARK where the circuit itself is a public input, at significant performance penalty, or else (b) do all those trusted setups somehow, maybe by paying some participants that represent your threat model for soundness.  

I wrote that too hastily.  We actually cannot do trusted setups for Groth16 with a para-thread because we ban randomness from the block execution function.  We could add another para-thread-like operation for Groth16 trusted setups, but doing so requires first justifying that our validators represent a good threat model for soundness. 

---

Anyone who want a ZoKrates-like system without any trusted setup right now should use [ZkVM](https://github.com/stellar/slingshot/tree/main/zkvm) which [employs aggregation of bulletproofs by dropping the mempool](https://github.com/stellar/slingshot/blob/main/zkvm/docs/zkvm-design.md#scalability).  In verifier time, I believe ZkVM should reduce the constant on the O(chain_size * block_size) term making the O(chain_size) term dominant.

Afaik, we've no need for an ZoKrates DSL with bulletproofs per se because any design constraint that favors avoiding trusted setups should appear early before you choose your R1CS DSL.  That said, ZkVM uses R1CS too, so some of the ZoKrates DSL may simply work.  I'm afraid the verification time would still nerf you into coin mixer land though.

In future, you could maybe build on [halo](https://github.com/ebfull/halo) after more researchers explore that design and should improve the verification time dramatically.

**Comment by danielsonggit** [comment]
@edisinovcic  Thanks for your comments. We think it is better to use our proposed toolchain since we can provide a DSL or even some advanced Language. Our initial analysis shows that Zokrates DSL should be sufficient for us. During the project, if we find that this is not the case, we may have to redesign it. At the moement, we just refer to the Zokrates’s design.

You are right on the trusted set up issue. We recommend the use of bulletproof to avoid trusted setup process both on parachain and Relay Chain.

@burdges  About universal circuit, the best result  is form the [Ágnes Kiss, Thomas Schneider paper](https://eprint.iacr.org/2016/093.pdf), the size of universal circuit is 20nlogn, with n gate. So the performance may be awkward.
We will do more research on zkvm, thank you so much for your kind advice.

**Comment by burdges** [comment]
I kinda doubt universal boolean circuits have similar performance concerns with even arithmetic circuits, much less SNARKs with universal and updateable SRSs, like [marlin](https://github.com/scipr-lab/Marlin) and [PLONK](https://eprint.iacr.org/2019/953.pdf).  

These still have trusted setups for universal SRSs, but they do not depend upon the arithmetic circuit being used, unlike groth16.

**Comment by lucasvo** [comment]
I just wanted to share a bulletproofs backend that Qed-it built for ZoKrates that I believe implements a lot of what you are trying to do here: https://qed-it.github.io/zkinterface-wasm-demo/

**Comment by danielsonggit** [comment]
@lucasvo Thank you very much for your kindness to  share the project with us!

**Pull request closed without merging**
