### PR TITLE
Substrate runtime in SGX enclave

### PR DESCRIPTION
**Pull request by brenzi**
## Grant Application

This application is (select one):
- [x] Speculative (use this by default)
- [ ] an RFP response

###

This application is (select one):
- [ ] Public (fully)
- [x] Public with private finances

### Abstract

SCS suggests an extension to substrate allowing to call the runtime modules inside an Intel SGX enclave. This would allow modules to read and modify an encrypted state that can't be accessed outside a set of provisioned enclaves. The application also includes the implementation of an enclave provisioning procedure allowing to modify the set of enabled enclaves dynamically.

Use cases demanding transaction privacy could be implemented on substrate with this extension.

## Checklist
- [x] The [grants](https://github.com/w3f/Web3-collaboration/blob/master/grants/grants.md) document has been read and understood.
- [x] The [Google Form](https://docs.google.com/forms/d/e/1FAIpQLSfMfjiRmDQDRk-4OhNASM6BAKii7rz_B1jWtbCPkUh6N7M2ww/viewform) will be completed accurately. Note that the Google Form requires the pull request URL.
- [x] Abstract (above) is succinct and complete.
- [x] The application is being included into the correct directory: either '[targeted](https://github.com/w3f/Web3-collaboration/tree/master/grants/targeted)' or '[speculative](https://github.com/w3f/Web3-collaboration/tree/master/grants/speculative)'.
- [x] The application includes a project description.
- [x] The application includes all names of team members.
- [x] The application includes a description of the team's experience.
- [x] The application includes all necessary GitHub and LinkedIn links.
- [x] The application specifies the development language and the reason for choosing it.
- [x] The "Development Roadmap" section in the application has a timeline of development.
- [ ] The "Development Roadmap" section in the application has an estimate of funds required.
- [x] The "Development Roadmap" section gives an indication of the team's long term plans.

### CODE REVIEW

**Comment by burdges** [comment]
I'm extremely dubious about using this for privacy, but several use cases exist, including bridges, so sounds reasonable. 

We should review the attacks on SGX like FORESHADOW to see if they benefit from being inside an enclave.  Assuming so, we should keep access completely under the node operator's control, meaning parachains that use this would interact differently with polkadot's shared security model.  In this case, we should be extra careful about anything unaudited like smart contracts running in an enclave.

**Comment by brenzi** [comment]
@burdges I need to do more research on FORESHADOW myself. It does concern me in the case of unpermissioned blockchains as we can't be sure validators are patched (adversaries would run unpatched SGX). Use cases might be restricted to permissioned chains running validators on patched systems because we can't allow anyone to join the validator set if SGX remote attestation is broken by FORESHADOW. However, I'm wondering if we can leverage secure boot to make sure we're running on a patched system.

**Comment by burdges** [comment]
I'm no expert in this area but I doubt patching completely fixes anything, simply because they vulnerabilities run so deep, and the patches are a combined effort across microcode, os, and applications, which sounds fragile.  It's still better than nothing for applications like bridges.  Instead, I think the primary defense comes through node specialization, which complicates on-chain upgrades, but hey.

**Comment by brenzi** [comment]
I'd like to adjust my statement above. I was pointed to a [thread](https://software.intel.com/en-us/forums/intel-software-guard-extensions-intel-sgx/topic/798777) and an [issue](https://github.com/intel/linux-sgx/issues/340) where Intel states about IAS:

>The CONFIGURATION_NEEDED status is returned under two separate conditions:
>  An EPID has been provisioned to the platform and sealed against the most recent Trusted Computing Base (TCB) specification for the platform but hyper-threading is enabled.
>  The platform has not been provisioned against the current platform TCB (GROUP_OUT_OF_DATE) and the platform does not have the security sensitive BIOS microcode update applied.

So IAS (API V3) can actually tell if hyperthreading is enabled and the latest microcode is active.

My fear that remote attestation may not work for unpermissioned chains seems incorrect. All the better. But of course, it is a race against time....

**Pull request merged**
