### PR TITLE
Zerochain

### PR DESCRIPTION
**Pull request by osuketh**
## Grant Application

This application is (select one):
- [x] Speculative (use this by default)
- [ ] an RFP response

###

This application is (select one):
- [ ] Public (fully)
- [x] Public with private finances

### Abstract

We are building a privacy-protecting parachain for Polkadot using zero-knowledge proofs. Zerochain is the first implementation of account-based blockchain for privacy-preserving  and the first substrate node applied zero-knowledge proofs. 

## Checklist
- [x] The [grants](https://github.com/w3f/Web3-collaboration/blob/master/grants/grants.md) document has been read and understood.
- [x] The [Google Form](https://docs.google.com/forms/d/e/1FAIpQLSfMfjiRmDQDRk-4OhNASM6BAKii7rz_B1jWtbCPkUh6N7M2ww/viewform) will be completed accurately. Note that the Google Form requires the pull request URL.
- [x] Abstract (above) is succinct and complete.
- [x] The application is being included into the correct directory: either '[targeted](https://github.com/w3f/Web3-collaboration/tree/master/grants/targeted)' or '[speculative](https://github.com/w3f/Web3-collaboration/tree/master/grants/speculative)'.
- [x] The application includes a project description.
- [x] The application includes all names of team members.
- [x] The application includes a description of the team's experience.
- [x] The application includes all necessary links (e.g. GitHub and LinkedIn)
- [x] The "Development Roadmap" section in the application has a timeline of development ("milestones").
- [x] The "Development Roadmap" section in the application has an estimate of funds required.
- [x] The "Development Roadmap" section gives an indication of the team's long term plans.
- [x] The "Development Roadmap" section includes [documentation](https://github.com/w3f/Web3-collaboration/blob/master/grants/grants.md#documentation) as a deliverable for at least one milestone.

### CODE REVIEW

**Comment by burdges** [comment]
Can you tell me how this compares with the [QuisQuis](https://eprint.iacr.org/2018/990.pdf) proposal?

**Comment by osuketh** [comment]
QuisQuis is basically a hybrid UTXO and account model using the updatable public key. The property also solves some problems with privacy-preserving as like Zerochain.
- growing UTXO and metadata(nullifier or key image): in Zcash and Monero
- interactive communication: needed in Grin.

A big concern of QuisQuis, however, is all users have to download the list of all updated keys to find out which one belongs to them or be a full node for tracking their updated keys because there is no way to know which is their own updated key corresponding to their secret key.

I thought the QuisQuis's updatable key approach could be applied to Zerochain for getting the address anonymity, but I could not find any workaround the above issue. In addition, I think it is more difficult to protect from front-running attacks in QuisQuis.

**Comment by burdges** [comment]
So QuisQuis permutes the account list?  Ugh, I never noticed that from the paper. 

I think one could permute an account list in a way only the secret key holder could track, but then you cannot really pay into accounts.  I suspect pairings might yield accounts where only payers knowing some semi-public data about the account track it, but that opens another can of worms.

**Comment by osuketh** [comment]
Ya. And I cannot understand how to fetch the current balance without all accounts tracking. Each user might need to send zk proof to get their balance. However, the updatable key is an interesting approach I think.

**Comment by burdges** [comment]
I'd worry about the salability of permuting the accounts list too.  We've many obviously problematic blockchain scheme that assume users can scan the whole chain.  Accounts improve this but eventually users cannot even scan the accounts database.

Ignoring that, we might have a locator secret key `lsk` and a spending secret key `ssk` in an ElGammal triple `(P, lsk *, ssk * P)`.  You might need a proof-of-knowledge of both `ssk` and `p` such that `P = p G` to initially create an `lsk` value.  And then an `lsk` to pay into an account.

**Comment by osuketh** [comment]
So, `lsk` works as a refreshable key, right? You can generate a new `lsk` whenever you want, though it also puts an additional burden on users.

I think it is difficult for non-utxo model to get the Zcash-level anonymity guarantee rather than Monero-level. This is one of the most interesting topics I would like to tackle in the mid-term.

**Comment by burdges** [comment]
If I understood, your primary goal is to implement [Zether](https://eprint.iacr.org/2019/191.pdf) using zcash's toolchain, yes?  cool. :)

**Comment by osuketh** [comment]
> If I understood, your primary goal is to implement Zether using zcash's toolchain, yes?

Exactly. We use zcash's toolchain instead of sigma-bullets because we can use more reliable code and would need more succinctness for future works.

> Can you make any comments about how much of the paper is required to get something working?

We’ve already implemented [Elgamal encryption](https://github.com/LayerXcom/zero-chain/blob/master/core/crypto/src/elgamal.rs),  [Zero-knowledge relations](https://github.com/LayerXcom/zero-chain/blob/master/core/proofs/src/circuit_transfer.rs)(Section6 in the paper), [key components](https://github.com/LayerXcom/zero-chain/blob/master/core/keys/src/lib.rs), and zcash's toolchain for no_std([pairing](https://github.com/LayerXcom/zero-chain/tree/master/core/pairing) / [jubjub](https://github.com/LayerXcom/zero-chain/tree/master/core/jubjub) / [verifier part of bellman](https://github.com/LayerXcom/zero-chain/tree/master/core/bellman-verifier)) to integrate with [our confidential transfer SRML](https://github.com/LayerXcom/zero-chain/blob/master/runtime/src/conf_transfer.rs).

We need some refactoring of our code and careful code reviews towards production grade.

In addition, we will implement the front-running protection explained in section3.1, but a lock/unlock functionality(Section3.2) would not be needed because we haven't had smart contracts yet.
Anonymous transfer(Appendix D) will also be required to hide the sender and receiver addresses.

>do any parts of it make you feel "nervous", eiother about the security or the implementation? 

We feel the implementation of the statement in circuit is the most nervous part for us, and also we have to benchmark how many epochs(in Section3.1) are appropriate for the tradeoff between security and UX.

**Comment by osuketh** [comment]
FYI, recent talk about Zether at Zkproof workshop.
https://youtu.be/Nm0tn0vH194

**Pull request merged**
