### PR TITLE
The D🍩H-nut Protocol, Terrifying Terminology 👻, and the Web3 Infrastructure Directory ⚙️

### PR DESCRIPTION
**Pull request by burrrata**
## Grant Application

This application is (select one):
- [x] Speculative (use this by default)
- [ ] an RFP response

###

This application is (select one):
- [x] Public (fully)
- [ ] Public with private finances

### Abstract

[Provide a brief description of your project here (summarise key points). 

If your application is part of a programme, please mention which in the first line of the abstract.

The details should be in the application 'document' that you add to this repo via a pull request.]

## Checklist
- [x] The [grants](https://github.com/w3f/Web3-collaboration/blob/master/grants/grants.md) document has been read and understood.
- [x] The [Google Form](https://docs.google.com/forms/d/e/1FAIpQLSfMfjiRmDQDRk-4OhNASM6BAKii7rz_B1jWtbCPkUh6N7M2ww/viewform) will be completed accurately. Note that the Google Form requires the pull request URL.
- [x] Abstract (above) is succinct and complete.
- [x] The application is being included into the correct directory: either '[targeted](https://github.com/w3f/Web3-collaboration/tree/master/grants/targeted)' or '[speculative](https://github.com/w3f/Web3-collaboration/tree/master/grants/speculative)'.
- [x] The application includes a project description.
- [x] The application includes all names of team members.
- [x] The application includes a description of the team's experience.
- [x] The application includes all necessary GitHub and LinkedIn links.
- [x] The application specifies the development language and the reason for choosing it.
- [x] The "Development Roadmap" section in the application has a timeline of development.
- [x] The "Development Roadmap" section in the application has an estimate of funds required.
- [x] The "Development Roadmap" section gives an indication of the team's long term plans.

### CODE REVIEW

**Comment by burrrata** [comment]
So, I have 2 grant applications now:
- the daonut protocol 
- terrifying terminology

The daonut protocol is the priority, but the terminology thing is also important (and very small) and could be fulfilled on the side as well. Thanks! 🍩

**Comment by burrrata** [comment]
Btw, development of the Substrate/Rust implementation is happening here: https://github.com/burrrata/DOH

**Comment by burrrata** [comment]
Added a proposal for research into a Web3 Infrastructure Directory :)

**Comment by burrrata** [comment]
Updated roadmap with milestones.

Also updated the content to be more descriptive of where the project is at today because when the grant was originally proposed there were a lot of tentative things that have been cleared up.

**Comment by burrrata** [comment]
Added initial description and updated roadmap with milestones :)

**Comment by burrrata** [comment]
I never got a response on any of these. That's really lame. At least add a comment explaining why it's not a good fit and you're closing the PR.

**Comment by EdwardAThomson** [comment]
I thought this was discussed on the phone calls we had. I had assumed there was resolution, but perhaps there wasn't. Apologies.

Let's have a catch up?

**Comment by burrrata** [comment]
Must be a miscommunication then. Last I heard from the W3F team Jack and Ryan wanted to chat. When I asked what they wanted to talk about they said they would email me. They never did. I dunno ¯\_(ツ)_/¯

Anyways, saw you closing this and wanted to figure out why. Feedback and complete information is always good :) I'll check Riot now

**Comment by EdwardAThomson** [comment]
I understand we are not proceeding here.

**Pull request closed without merging**
